import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import ContextProvider from "./context/ContextProvider";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geist = Geist({
  weight: '400'
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "KeenKeeper",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geist.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <Navbar></Navbar>
      <ContextProvider>
      {children}
      <Footer></Footer>
      </ContextProvider>
      <ToastContainer></ToastContainer>
      </body>
    </html>
  );
}
